title: Erwachen
description: Erwachen description
theme: just-the-docs

url: https://just-the-docs.github.io

# Plugins:

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2

# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
search.tokenizer_separator: /[\s/]+/

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# Color scheme supports "light" (default) and "dark"
# color_scheme: dark

